INSERT INTO EMPLOYEE("ID", "DEPARTMENT_ID", "CHEIF_ID", "NAME", "SALARY")
VALUES (29, 9, 28, 'Peter', 50000);
INSERT INTO EMPLOYEE("ID", "DEPARTMENT_ID", "CHEIF_ID", "NAME", "SALARY")
VALUES (30, 9, 28, 'Marina', 40000);
INSERT INTO EMPLOYEE("ID", "DEPARTMENT_ID", "CHEIF_ID", "NAME", "SALARY")
VALUES (31, 9, 28, 'Sergey', 30000);